[package]
name = "thmbs"
version = "0.1.2"
edition = "2024"
description = "ls(1) listing supplemented with inline image thumbnails"
license = "MIT"
repository = "https://github.com/kloki/thmbs"

[[bin]]
name = "thmbs"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
base64 = "0.22"
imagesize = "0.13"
jiff = "0.2"
libc = "0.2"

[profile.release]
lto = "thin"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
